Repository habitat-sh/builder, pull requests merged in 2018-02, with the labels that each got.

#112 Add ability for worker to bind to local docker socket for testing exports
  .studiorc
  components/builder-worker/src/runner/docker.rs
  components/builder-worker/src/runner/mod.rs
  components/builder-worker/src/runner/studio.rs
  support/linux/provision.sh
Labels: enhancement

#210 [builder-worker] Re-work job streaming & introduce log sections.
  components/builder-worker/src/error.rs
  components/builder-worker/src/runner/docker.rs
  components/builder-worker/src/runner/job_streamer.rs
  components/builder-worker/src/runner/log_pipe.rs
  components/builder-worker/src/runner/mod.rs
  components/builder-worker/src/runner/studio.rs
Labels: bug, enhancement

#211 [builder-worker] Temporarily remove `--tag-latest` when running Docker exporter
  components/builder-worker/src/runner/docker.rs
Labels: STABILITY, bug
