Repository habitat-sh/builder, pull requests merged in 2018-07, with the labels that each got.

#512 Allow HAB_FEAT_IGNORE_LOCAL to get into the worker studio
  components/builder-worker/src/runner/studio.rs
Labels: C-bug

#520 Mount drive to /mnt, NOT /hab
  terraform/scripts/foundation.sh
Labels: A-builder, C-bug, I-linux, V-bldr, V-infra

#528 [BREAKING/depot] Updates due to PackageTarget changes in habitat-sh/core#37
  Cargo.lock
  components/builder-depot/src/backend/s3.rs
  components/builder-depot/src/config.rs
  components/builder-depot/src/lib.rs
  components/builder-depot/src/server.rs
  components/builder-protocol/src/originsrv.rs
Labels: A-builder, C-chore, E-less-easy, I-linux, L-rust, T-breaking, V-bldr

#539 [core] Add new PackageTarget from habitat-sh/core#42.
  Cargo.lock
Labels: A-builder, C-feature, E-easy, I-linux, L-rust, V-bldr, V-devx, X-feature

#540 [ci] Update to Rust 1.27.1.
  .travis.yml
Labels: C-chore, E-easy, I-linux

#549 Fix the assignment of the various PID variables in the db test script
  components/builder-db/tests/db/start.sh
Labels: X-fix

#561 Fix a minor issue with finding the files to run shellcheck against
  .studiorc
  components/builder-api-proxy/habitat/hooks/health_check
  components/builder-api-proxy/habitat/hooks/init
  components/builder-api/habitat/hooks/health_check
  components/builder-api/habitat/hooks/run
  components/builder-datastore/hooks/init
  components/builder-datastore/hooks/run
  components/builder-jobsrv/habitat/hooks/init
  components/builder-jobsrv/habitat/hooks/run
  components/builder-minio/habitat/hooks/init
  components/builder-minio/habitat/hooks/run
  components/builder-originsrv/habitat/hooks/init
  components/builder-originsrv/habitat/hooks/run
  components/builder-router/habitat/hooks/run
  components/builder-sessionsrv/habitat/hooks/init
  components/builder-sessionsrv/habitat/hooks/run
  components/builder-web/bin/build-css
  components/builder-worker/habitat/hooks/run
  test/shellcheck.sh
Labels: T-DO-NOT-MERGE, X-fix

#560 Adds validation of minio write to s3 uploads
  components/builder-depot/src/backend/s3.rs
  components/builder-depot/src/error.rs
Labels: A-builder, C-chore, P-3, T-emergent, V-bldr, X-fix
