Repository habitat-sh/builder, pull requests merged in 2019-01, with the labels that each got.

#865 Remove Garrett Amini from CODEOWNERS
  CODEOWNERS
Labels: Expeditor: Exclude from Changelog

#869 Allow setting of datastore superuser password via config
  components/builder-datastore/default.toml
  components/builder-datastore/hooks/init
Labels: X-feature

#867 Use the IP address of API service, not my sys.ip in backend block
  components/builder-api-proxy/habitat/config/nginx.conf
  components/builder-api-proxy/habitat/default.toml
Labels: X-fix

#904 cargo update
  Cargo.lock
  components/builder-protocol/src/jobsrv.rs
Labels: Expeditor: Exclude from Changelog
