Repository habitat-sh/builder, pull requests merged in 2019-02, with the labels that each got.

#881 Replace Strings and &strs with type-safe habitat_core::ChannelIdent type
  Cargo.lock
  components/builder-api/src/server/resources/channels.rs
  components/builder-api/src/server/resources/jobs.rs
  components/builder-api/src/server/resources/pkgs.rs
  components/builder-api/src/server/services/memcache.rs
  components/builder-core/src/api_client.rs
  components/builder-core/src/build_config.rs
  components/builder-db/src/models/channel.rs
  components/builder-db/src/models/jobs.rs
  components/builder-db/src/models/origin.rs
  components/builder-db/src/models/package.rs
  components/builder-jobsrv/src/server/scheduler.rs
  components/builder-worker/src/config.rs
  components/builder-worker/src/runner/postprocessor.rs
  components/builder-worker/src/runner/publisher.rs
  components/builder-worker/src/runner/studio.rs
  components/builder-worker/src/runner/toml_builder.rs
Labels: Expeditor: Exclude from Changelog

#910 Fix BoxKeyPair::encrypt return type
  Cargo.lock
  components/builder-api/src/server/resources/origins.rs
  components/builder-core/src/access_token.rs
  components/builder-core/src/integrations.rs
  components/builder-jobsrv/src/server/worker_manager.rs
Labels: X-fix

#933 Expose target in bldr job status
  components/builder-jobsrv/src/data_store.rs
  components/builder-protocol/src/jobsrv.rs
  components/builder-worker/src/server.rs
Labels: A-builder, C-feature, V-bldr, X-feature
